
---

render:
- templates:
  - templates/example.tpl
  destination: kaiser-demo/example/templates
  engine: golang
- templates:
  - templates/example.jsonnet
  destination: kaiser-demo/example/templates
  engine: jsonnet

kaiser-demo:
  hello: World
