---

render:
- templates:
  - templates/golang
  destination: templates/golang
  engine: golang
- templates:
  - templates/jsonnet
  destination: templates/jsonnet
  engine: jsonnet


demo_module:
  hello: world
