
---

render:
- templates:
  - templates/example.tpl
  destination: kaiser_demo/example/templates
  engine: golang
- templates:
  - templates/example.jsonnet
  destination: kaiser_demo/example/templates
  engine: jsonnet

kaiser_demo:
  hello: World
